export const AMMUNITIONS_SUCCESS = "AMMUNITIONS_SUCCESS";
export const AMMUNITIONS_FAIL = "AMMUNITIONS_FAIL";
export const BULLETS_DETAILS_SUCCESS = "BULLETS_DETAILS_SUCCESS";
export const BULLETS_DETAILS_FAIL = "BULLETS_DETAILS_FAIL";